// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Jo;

privileged aspect Jo_Roo_JavaBean {
    
    public String Jo.getName() {
        return this.name;
    }
    
    public void Jo.setName(String name) {
        this.name = name;
    }
    
}
