// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Jo;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Jo_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Jo.entityManager;
    
    public static final List<String> Jo.fieldNames4OrderClauseFilter = java.util.Arrays.asList("name");
    
    public static final EntityManager Jo.entityManager() {
        EntityManager em = new Jo().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Jo.countJoes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Jo o", Long.class).getSingleResult();
    }
    
    public static List<Jo> Jo.findAllJoes() {
        return entityManager().createQuery("SELECT o FROM Jo o", Jo.class).getResultList();
    }
    
    public static List<Jo> Jo.findAllJoes(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Jo o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Jo.class).getResultList();
    }
    
    public static Jo Jo.findJo(Long id) {
        if (id == null) return null;
        return entityManager().find(Jo.class, id);
    }
    
    public static List<Jo> Jo.findJoEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Jo o", Jo.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Jo> Jo.findJoEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Jo o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Jo.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Jo.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Jo.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Jo attached = Jo.findJo(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Jo.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Jo.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Jo Jo.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Jo merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
